# WebSocket 服务器配置
[server]
name = "web-socket-test"
# 服务器监听地址
address = ":8080"
# 是否启用调试模式
debug = true

[websocket]
# 缓冲区大小设置
read_buffer_size = 1024
write_buffer_size = 1024
# 最大消息大小（字节）
max_message_size = 512000
# 是否启用压缩
enable_compression = true

# 连接配置
[connection]
# 最大并发连接数
max_connections = 1000
# 心跳超时时间（秒）
heartbeat_timeout = 60
# 写入超时时间（秒）
write_timeout = 10
# 读取超时时间（秒）
read_timeout = 10

# 跨域配置
[cors]
# 允许的源域名列表，* 表示允许所有
allowed_origins = ["*"]
# 是否允许所有源
allow_all = true