# 日志配置文件

# 全局日志级别
log_level = "info"

# 日志输出路径
[log]
# 日志文件路径
file = "logs/app.log"
# 是否同时输出到控制台
console = true
# 日志文件最大大小(MB)
max_size = 100
# 保留的日志文件数量
max_backups = 7
# 保留日志文件的最大天数
max_age = 30
# 是否压缩历史日志
compress = true

# 访问日志配置
[access_log]
# 访问日志文件路径
file = "logs/access.log"
# 是否启用访问日志
enable = true
# 访问日志文件最大大小(MB) 
max_size = 100
# 保留的访问日志文件数量
max_backups = 7
# 保留访问日志文件的最大天数
max_age = 30
# 是否压缩历史访问日志
compress = true
