# 普通日志配置
[log]
# 基础日志目录
base_dir = "./logs"
# 是否同时输出到控制台
console = true
# 单个日志文件的最大大小，单位是 MB
max_size = 100
# 保留的旧日志文件个数
max_backups = 10
# 保留的日志文件的最大天数
max_age = 30
# 是否压缩旧日志文件
compress = true

# 不同级别日志配置
[log.levels]
info = "info.log"
warn = "warn.log"
error = "error.log"
debug = "debug.log"
fatal = "fatal.log"

# 访问日志配置
[access_log]
# 访问日志文件路径
file = "./logs/access.log"
# 是否启用访问日志
enable = true
# 单个日志文件的最大大小，单位是 MB
max_size = 100
# 保留的旧日志文件个数
max_backups = 10
# 保留的日志文件的最大天数
max_age = 30
# 是否压缩旧日志文件
compress = true